### ISSUE TITLE
Check file ready to download.

### ISSUE THREAD

**Issue by metalex9** [metalex9/TorrentFlow#12]
Initial testing showed that the program will attempt to download files that aren't being done copied on the seedbox. It needs to check that the files are fully moved and ready to download.

**Comment by miracle091** [comment]
This can be resolved using a check first and after the download using MD5 or CRC32 string or a more simple method just to check if the files exist or not

**Comment by metalex9** [comment]
I was thinking it could double check the file before downloading to see if its contents/size changed. If it can be helped, I'd prefer not to download the file until I know it's ready.

**Comment by metalex9** [comment]
But a post-download verification check is also a good idea.
