### ISSUE TITLE
FtpClient returns an empty list for directories matching ".*\[.+\].*"

### ISSUE THREAD

**Issue by metalex9** [metalex9/TorrentFlow#23]
Repro: Create a directory whose name matches the regex `.*\[.+\].*` (that is, it has to have opening and closing brackets with some text inside). Put some files in the new directory, and then run the program. It will not download any of the files, because FtpClient.GetListing returns an empty list.

**Comment by metalex9** [comment]
Okay so it turns out spaces aren't the issue... I'll see if I can figure out what's going on.

**Comment by metalex9** [comment]
Looks like this is an encoding issue.

**Comment by metalex9** [comment]
So uh...this appears to be an issue with System.Net.FtpClient (I've been in the source for that). Not sure what workaround we can do here.

**Comment by miracle091** [comment]
Change the library, fix the error directly on the source code and recompile it or i don't know.
